function [controlPort, dataPort, configFileName, loadConfig, showVideoChoice, videoSourceId] = configDialog(settingsFileName, showVideoFlag, guiPath, singlePort)
if nargin<1, settingsFileName = ''; end
if nargin<2, showVideoFlag = false; end
if nargin<3, guiPath = ''; end
if nargin<4, singlePort = 0; end

% Prepare the default settings
controlPort = [];
dataPort = [];
configFileName = '';
loadConfig = 0;
showVideoChoice = showVideoFlag;
videoSourceId = 0;

comPortsOptions = 1:100;
comPortChoice = arrayfun(@(c) sprintf('COM%d',c), comPortsOptions, 'UniformOutput', false);
comPortDefaults = comPortsOptions(1:2);

if exist(settingsFileName, 'file')
    [configPathName, configFileName] = readSettings(settingsFileName);
else   
    configPathName = [guiPath '\chirpConfigs'];
    configFileName = 'test.cfg';
end
controlPortNum = '';
dataPortNum = '';

% Update the relative path
if ~isempty(configPathName)
    if strcmp(configPathName(1:2),'.\') || strcmp(configPathName(1:2),'./')
        configPathName = [guiPath '\' configPathName(3:end)];
    end
    if strcmp(configPathName(1),'\') || strcmp(configPathName(1),'/')
        configPathName = [guiPath '\' configPathName(2:end)];
    end
end

% Update the COM port numbers if needed
if ~isnumeric(controlPortNum) || ~isnumeric(dataPortNum)
    [controlPortNum, dataPortNum] = findDemoComPorts();
    if isempty(controlPortNum) || isempty(dataPortNum)
        controlPortNum = comPortDefaults(1);
        dataPortNum = comPortDefaults(2);
    end
end
if singlePort == 1
    dataPortNum = controlPortNum;
end

% Control port selection
hDialog = dialog('Position',[300 300 420 260],'Name','Configuration');
uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[20 210 100 40],...
    'HorizontalAlignment','left',...
    'String','Select control port:');

popup_control = uicontrol('Parent',hDialog,...
    'Style','popupmenu',...
    'Position',[20 200 100 30],...
    'String',comPortChoice,...
    'Value', controlPortNum);

% Data port selection
uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[140 210 100 40],...
    'HorizontalAlignment','left',...
    'String','Select data port:');

popup_data = uicontrol('Parent',hDialog,...
    'Style','popupmenu',...
    'Position',[140 200 100 30],...
    'String', comPortChoice,...
    'Value', dataPortNum);

% Webcam selection
if (showVideoFlag == true)
    uicontrol('Parent',hDialog,...
        'Style','text',...
        'Position',[20 150 180 40],...
        'HorizontalAlignment','left',...
        'String','Select webcam:');

    availableWebCams = webcamlist;
    popup_camera = uicontrol('Parent',hDialog,...
        'Style','popupmenu',...
        'Position',[20 140 180 30],...
        'String',availableWebCams,...
        'Value',1);

    hWebcamConfig = uicontrol('Parent',hDialog,...
        'Style','checkbox',...
        'String','Enable Webcam',...
        'Position',[220 150 100 20],...
        'Value',0);
else
    uicontrol('Parent',hDialog,...
        'Style','text',...
        'Position',[20 150 200 40],...
        'HorizontalAlignment','left',...
        'String','Video preview disabled!');
end

% Chirp configuration selection
uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[20 80 200 40],...
    'HorizontalAlignment','left',...
    'String','Select chirp configuration file:');

hFileName = uicontrol('Parent', hDialog,...
    'Style','text',...
    'Position',[20 60 320 40],...
    'HorizontalAlignment','left',...
    'String', configFileName);

hFileSelect = uicontrol('Parent',hDialog,...
    'Style', 'pushbutton',...
    'Position',[340 85 60 20],...
    'String','Browse',...
    'Callback',@configFileSelect_callback);

setappdata(hFileSelect,'configFileName', [configPathName, '\', configFileName]);

% Load configuration selection
hLoadConfig = uicontrol('Parent',hDialog,...
    'Style','Radio',...
    'String','Load Configuration',...
    'Position',[20 20 160 20],...
    'Value',1);

% Extract the outputs
uicontrol('Parent',hDialog,...
    'Position',[200 20 60 20],...
    'String','Done',...
    'Callback',@done_callback);

% Wait for d to close before running to completion
uiwait(hDialog);

    function [pathname, filename] = configFileSelect_callback (source, ~)
    [filename, pathname] = uigetfile({'*.cfg'},...
        'Select Chirp configuration File', ...
        getappdata(source, 'configFileName'));
    hFileName.String = filename;
    setappdata(source, 'configFileName', [pathname, filename]);
    end
    
    function done_callback (~, ~)
        controlPort = popup_control.Value;
        dataPort = popup_data.Value;
        loadConfig = hLoadConfig.Value;
        configFileName = getappdata(hFileSelect, 'configFileName');
        if (showVideoFlag == true)
            showVideoChoice = hWebcamConfig.Value;
            videoSourceId = popup_camera.Value;
        end
        delete(gcf);
    end
end